# Generated by Django 5.2 on 2026-01-26 10:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=45)),
                ('port', models.IntegerField()),
                ('stream_url', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'infrastructure_camera',
            },
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('total_slots', models.IntegerField()),
                ('available_slots', models.IntegerField(default=0)),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'parking_lot',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='parking_lot_latitud_5c6073_idx'), models.Index(fields=['is_open'], name='parking_lot_is_open_ae2829_idx')],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='infrastructure.parkinglot')),
            ],
            options={
                'db_table': 'floor',
                'ordering': ['level'],
                'unique_together': {('parking_lot', 'level')},
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Motorbike', 'Motorbike')], max_length=20)),
                ('capacity', models.IntegerField()),
                ('available_slots', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='infrastructure.floor')),
            ],
            options={
                'db_table': 'zone',
            },
        ),
        migrations.CreateModel(
            name='CarSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('x1', models.IntegerField(blank=True, null=True)),
                ('y1', models.IntegerField(blank=True, null=True)),
                ('x2', models.IntegerField(blank=True, null=True)),
                ('y2', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitored_slots', to='infrastructure.camera')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='infrastructure.zone')),
            ],
            options={
                'db_table': 'car_slot',
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='infrastructure.zone'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['vehicle_type'], name='zone_vehicle_94cad4_idx'),
        ),
        migrations.AddIndex(
            model_name='carslot',
            index=models.Index(fields=['status'], name='car_slot_status_d1f059_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='carslot',
            unique_together={('zone', 'code')},
        ),
    ]
