# Generated by Django 5.2 on 2026-01-26 10:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('vehicle_id', models.UUIDField()),
                ('vehicle_license_plate', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('parking_lot_id', models.UUIDField()),
                ('parking_lot_name', models.CharField(max_length=255)),
                ('floor_id', models.UUIDField(blank=True, null=True)),
                ('floor_level', models.IntegerField(blank=True, null=True)),
                ('zone_id', models.UUIDField()),
                ('zone_name', models.CharField(max_length=100)),
                ('slot_id', models.UUIDField(blank=True, null=True)),
                ('slot_code', models.CharField(blank=True, max_length=20)),
                ('package_type', models.CharField(default='hourly', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('online', 'Online'), ('on_exit', 'On Exit')], max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('check_in_status', models.CharField(choices=[('not_checked_in', 'Not Checked In'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='not_checked_in', max_length=20)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('qr_code_data', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'booking',
                'indexes': [models.Index(fields=['user_id'], name='booking_user_id_acf7f7_idx'), models.Index(fields=['slot_id'], name='booking_slot_id_a06fda_idx'), models.Index(fields=['check_in_status'], name='booking_check_i_97b7eb_idx'), models.Index(fields=['start_time', 'end_time'], name='booking_start_t_616860_idx')],
            },
        ),
        migrations.CreateModel(
            name='PackagePricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Motorbike', 'Motorbike')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'package_pricing',
                'unique_together': {('package_type', 'vehicle_type')},
            },
        ),
    ]
