# Generated by Django 4.2.27 on 2026-01-30 02:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('type', models.CharField(choices=[('emergency', 'Emergency'), ('theft', 'Theft'), ('vehicle_damage', 'Vehicle Damage'), ('accident', 'Accident'), ('suspicious_activity', 'Suspicious Activity'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('booking_id', models.UUIDField(blank=True, null=True)),
                ('parking_lot_id', models.UUIDField(blank=True, null=True)),
                ('zone_id', models.UUIDField(blank=True, null=True)),
                ('slot_id', models.UUIDField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('security_notified', models.BooleanField(default=False)),
                ('security_notified_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'incident',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='incident_user_id_3cbcd6_idx'), models.Index(fields=['status'], name='incident_status_9427e5_idx'), models.Index(fields=['type'], name='incident_type_2f961b_idx')],
            },
        ),
    ]
