# Generated by Django 4.2.27 on 2026-02-10 18:49

from django.db import migrations, models


def safe_migrate_booking(apps, schema_editor):
    """Add columns only if the table exists and columns are missing."""
    from django.db import connection
    with connection.cursor() as cursor:
        # Check if table exists
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.tables "
            "WHERE table_schema = DATABASE() AND table_name = 'bookings_booking'"
        )
        if cursor.fetchone()[0] == 0:
            return  # Table doesn't exist yet, skip

        cursor.execute("SHOW COLUMNS FROM bookings_booking")
        existing_cols = {row[0] for row in cursor.fetchall()}

        if 'extended_until' not in existing_cols:
            cursor.execute(
                "ALTER TABLE bookings_booking ADD COLUMN extended_until DATETIME NULL"
            )
        if 'hourly_end' not in existing_cols:
            cursor.execute(
                "ALTER TABLE bookings_booking ADD COLUMN hourly_end DATETIME NULL"
            )
        if 'hourly_start' not in existing_cols:
            cursor.execute(
                "ALTER TABLE bookings_booking ADD COLUMN hourly_start DATETIME NULL"
            )
        if 'late_fee_applied' not in existing_cols:
            cursor.execute(
                "ALTER TABLE bookings_booking ADD COLUMN late_fee_applied TINYINT(1) NOT NULL DEFAULT 0"
            )


def safe_add_incident_index(apps, schema_editor):
    """Add index only if it does not already exist."""
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.statistics "
            "WHERE table_schema = DATABASE() AND table_name = 'bookings_incident' "
            "AND index_name = 'incident_user_id_7ed37a_idx'"
        )
        if cursor.fetchone()[0] == 0:
            try:
                cursor.execute(
                    "CREATE INDEX incident_user_id_7ed37a_idx ON bookings_incident (user_id, id DESC)"
                )
            except Exception:
                pass  # Index creation is optional


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='booking',
            name='extended_until',
            field=models.DateTimeField(blank=True, help_text='Extended end time if user requests extension', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='hourly_end',
            field=models.DateTimeField(blank=True, help_text='Scheduled end time for hourly package', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='hourly_start',
            field=models.DateTimeField(blank=True, help_text='Scheduled start time for hourly package', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='late_fee_applied',
            field=models.BooleanField(default=False, help_text='Whether late fee was applied for overtime'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['user_id', '-id'], name='incident_user_id_7ed37a_idx'),
        ),
    ]