# Generated by Django 5.2 on 2026-01-26 10:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('license_plate', models.CharField(max_length=50, unique=True)),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Motorbike', 'Motorbike')], max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vehicle',
                'indexes': [models.Index(fields=['user_id'], name='vehicle_user_id_2e0a93_idx'), models.Index(fields=['license_plate'], name='vehicle_license_2d30a6_idx')],
            },
        ),
    ]
