using System.Collections.Generic;

namespace ParkingSim.API
{
    public static class MockDataProvider
    {
        private static readonly string[] SlotStatuses = { "available", "occupied", "reserved", "maintenance" };

        public static List<SlotData> GenerateMockSlots()
        {
            var slots = new List<SlotData>();

            // Floor 0 (B1): V1-01..V1-72 car slots
            for (int i = 1; i <= 72; i++)
            {
                string status;
                if (i <= 18)       status = "reserved";
                else if (i <= 36)  status = (i % 3 == 0) ? "reserved" : "available";
                else if (i <= 54)  status = (i >= 46) ? "occupied" : "available";
                else               status = (i <= 70) ? "occupied" : "available";
                slots.Add(new SlotData
                {
                    Id = $"00000000-0000-0000-0010-0000000000{i:D2}",
                    Zone = MockIds.ZONE_CAR_PAINTED_F1,
                    Code = $"V1-{i:D2}",
                    Status = status,
                    IsAvailable = status == "available",
                    Camera = null,
                    X1 = 0, Y1 = 0, X2 = 100, Y2 = 200
                });
            }

            // Floor 0 (B1): V2-01..V2-20 motorbike slots
            for (int i = 1; i <= 20; i++)
            {
                string status = PickStatus(i, 20);
                slots.Add(new SlotData
                {
                    Id = $"00000000-0000-0000-0012-0000000000{i:D2}",
                    Zone = MockIds.ZONE_MOTO_F1,
                    Code = $"V2-{i:D2}",
                    Status = status,
                    IsAvailable = status == "available",
                    Camera = null,
                    X1 = 0, Y1 = 600, X2 = 100, Y2 = 700
                });
            }

            // Floor 1: A-01..A-18 (Zone A), B-01..B-18 (Zone B)
            for (int i = 1; i <= 18; i++)
            {
                string statusA = (i == 2 || i == 10) ? "occupied" : (i == 1 ? "reserved" : "available");
                slots.Add(new SlotData
                {
                    Id = $"00000000-0000-0000-0013-0000000000{i:D2}",
                    Zone = MockIds.ZONE_CAR_PAINTED_F2,
                    Code = $"A-{i:D2}",
                    Status = statusA,
                    IsAvailable = statusA == "available",
                    Camera = null,
                    X1 = 0, Y1 = 0, X2 = 100, Y2 = 200
                });
                string statusB = (i <= 10) ? "reserved" : "available";
                slots.Add(new SlotData
                {
                    Id = $"00000000-0000-0000-0014-0000000000{i:D2}",
                    Zone = MockIds.ZONE_CAR_PAINTED_F2,
                    Code = $"B-{i:D2}",
                    Status = statusB,
                    IsAvailable = statusB == "available",
                    Camera = null,
                    X1 = 0, Y1 = 0, X2 = 100, Y2 = 200
                });
            }

            // Floor 1: C-01..C-20 motorbike
            for (int i = 1; i <= 20; i++)
            {
                string status = PickStatus(i, 20);
                slots.Add(new SlotData
                {
                    Id = $"00000000-0000-0000-0015-0000000000{i:D2}",
                    Zone = MockIds.ZONE_MOTO_F2,
                    Code = $"C-{i:D2}",
                    Status = status,
                    IsAvailable = status == "available",
                    Camera = null,
                    X1 = 0, Y1 = 600, X2 = 100, Y2 = 700
                });
            }

            // Garage G-01..G-10 (not in DB, but generated by Unity)
            for (int i = 1; i <= 10; i++)
            {
                slots.Add(new SlotData
                {
                    Id = $"00000000-0000-0000-0011-0000000000{i:D2}",
                    Zone = MockIds.ZONE_CAR_GARAGE_F1,
                    Code = $"G-{i:D2}",
                    Status = "available",
                    IsAvailable = true,
                    Camera = null,
                    X1 = 0, Y1 = 300, X2 = 100, Y2 = 500
                });
            }

            return slots;
        }

        public static List<FloorData> GenerateMockFloors()
        {
            return new List<FloorData>
            {
                new FloorData
                {
                    Id = MockIds.FLOOR_1,
                    ParkingLot = MockIds.LOT_1,
                    Level = 1,
                    Name = "Floor 1",
                    Zones = new List<ZoneData>
                    {
                        new ZoneData
                        {
                            Id = MockIds.ZONE_CAR_PAINTED_F1, Floor = MockIds.FLOOR_1,
                            FloorLevel = 1, Name = "Car Painted F1",
                            VehicleType = "Car", Capacity = 10, AvailableSlots = 6
                        },
                        new ZoneData
                        {
                            Id = MockIds.ZONE_CAR_GARAGE_F1, Floor = MockIds.FLOOR_1,
                            FloorLevel = 1, Name = "Car Garage F1",
                            VehicleType = "Car", Capacity = 5, AvailableSlots = 3
                        },
                        new ZoneData
                        {
                            Id = MockIds.ZONE_MOTO_F1, Floor = MockIds.FLOOR_1,
                            FloorLevel = 1, Name = "Motorbike F1",
                            VehicleType = "Motorbike", Capacity = 20, AvailableSlots = 12
                        }
                    }
                },
                new FloorData
                {
                    Id = MockIds.FLOOR_2,
                    ParkingLot = MockIds.LOT_1,
                    Level = 2,
                    Name = "Floor 2",
                    Zones = new List<ZoneData>
                    {
                        new ZoneData
                        {
                            Id = MockIds.ZONE_CAR_PAINTED_F2, Floor = MockIds.FLOOR_2,
                            FloorLevel = 2, Name = "Car Painted F2",
                            VehicleType = "Car", Capacity = 10, AvailableSlots = 8
                        },
                        new ZoneData
                        {
                            Id = MockIds.ZONE_CAR_GARAGE_F2, Floor = MockIds.FLOOR_2,
                            FloorLevel = 2, Name = "Car Garage F2",
                            VehicleType = "Car", Capacity = 5, AvailableSlots = 4
                        },
                        new ZoneData
                        {
                            Id = MockIds.ZONE_MOTO_F2, Floor = MockIds.FLOOR_2,
                            FloorLevel = 2, Name = "Motorbike F2",
                            VehicleType = "Motorbike", Capacity = 20, AvailableSlots = 15
                        }
                    }
                }
            };
        }

        public static List<BookingData> GenerateMockBookings()
        {
            var lot = new BookingLotInfo
            {
                Id = MockIds.LOT_1, Name = "ParkSmart Central",
                Address = "123 Nguyen Hue", Latitude = "10.762622", Longitude = "106.660172"
            };
            var floor1 = new BookingFloorInfo { Id = MockIds.FLOOR_1, Name = "Floor 1", Level = 1, ParkingLotId = MockIds.LOT_1 };

            return new List<BookingData>
            {
                MakeBooking(MockIds.BOOKING_1, MockIds.VEHICLE_CAR_1, "51A-224.56", "Car",
                    MockIds.ZONE_CAR_PAINTED_F1, "Car Painted F1", "Car", 10, 5,
                    "00000000-0000-0000-0010-000000000021", "V1-21", floor1, lot,
                    "08:00", "17:00", "not_checked_in", "20000.00", null, "2026-04-11T07:50:00Z"),
                MakeBooking(MockIds.BOOKING_2, MockIds.VEHICLE_CAR_2, "30H-567.89", "Car",
                    MockIds.ZONE_CAR_PAINTED_F1, "Car Painted F1", "Car", 10, 5,
                    MockIds.SLOT_A03, "A-03", floor1, lot,
                    "11:00", "13:00", "checked_in", "20000.00", "2026-04-01T11:05:00Z", "2026-04-01T10:55:00Z"),
                MakeBooking(MockIds.BOOKING_3, MockIds.VEHICLE_MOTO_1, "59P1-123.45", "Motorbike",
                    MockIds.ZONE_MOTO_F1, "Motorbike F1", "Motorbike", 20, 12,
                    MockIds.SLOT_M01, "M-01", floor1, lot,
                    "14:00", "16:00", "not_checked_in", "5000.00", null, "2026-04-01T13:50:00Z")
            };
        }

        private static BookingData MakeBooking(
            string bookingId, string vehicleId, string plate, string vType,
            string zoneId, string zoneName, string zoneVType, int cap, int avail,
            string slotId, string slotCode, BookingFloorInfo floor, BookingLotInfo lot,
            string startHour, string endHour, string checkInStatus, string price,
            string checkedInAt, string createdAt)
        {
            return new BookingData
            {
                Id = bookingId, UserId = MockIds.USER_1,
                Vehicle = new BookingVehicleInfo { Id = vehicleId, LicensePlate = plate, VehicleType = vType, Name = plate },
                PackageType = "hourly",
                StartTime = $"2026-04-01T{startHour}:00Z", EndTime = $"2026-04-01T{endHour}:00Z",
                Floor = floor,
                Zone = new BookingZoneInfo
                {
                    Id = zoneId, FloorId = floor.Id, Name = zoneName,
                    VehicleType = zoneVType, Capacity = cap, AvailableSlots = avail
                },
                CarSlot = new BookingSlotInfo { Id = slotId, ZoneId = zoneId, Code = slotCode, IsAvailable = false },
                ParkingLot = lot,
                PaymentType = "on_exit", PaymentStatus = "pending",
                CheckInStatus = checkInStatus, Price = price, CheckedInAt = checkedInAt,
                QrCodeData = "{\"booking_id\":\"" + bookingId + "\",\"user_id\":\"" + MockIds.USER_1 + "\"}",
                CreatedAt = createdAt
            };
        }

        public static List<VehicleData> GenerateMockVehicles()
        {
            return new List<VehicleData>
            {
                new VehicleData
                {
                    Id = MockIds.VEHICLE_CAR_1, UserId = MockIds.USER_1,
                    LicensePlate = "51A-224.56", VehicleType = "Car",
                    Brand = "Toyota", Model = "Camry", Color = "White",
                    IsDefault = true, Name = "51A-224.56"
                },
                new VehicleData
                {
                    Id = MockIds.VEHICLE_CAR_2, UserId = MockIds.USER_1,
                    LicensePlate = "30H-567.89", VehicleType = "Car",
                    Brand = "Honda", Model = "Civic", Color = "Black",
                    IsDefault = false, Name = "30H-567.89"
                },
                new VehicleData
                {
                    Id = MockIds.VEHICLE_MOTO_1, UserId = MockIds.USER_1,
                    LicensePlate = "59P1-123.45", VehicleType = "Motorbike",
                    Brand = "Honda", Model = "Wave", Color = "Red",
                    IsDefault = false, Name = "59P1-123.45"
                }
            };
        }



        // ~60% available, ~20% occupied, ~15% reserved, ~5% maintenance
        private static string PickStatus(int index, int total)
        {
            float ratio = (float)index / total;
            if (ratio < 0.60f) return "available";
            if (ratio < 0.80f) return "occupied";
            if (ratio < 0.95f) return "reserved";
            return "maintenance";
        }
    }
}
